spring.hibernate.dialect = org.hibernate.dialect.PostgreSQL9Dialect
spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=Dbnfkz_30072005

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration.access=900000
jwt.expiration.refresh=604800000

spring.jpa.hibernate.ddl-auto=create